abbreviations = {
    "major": {
        "Ascension": "ASC",
        "Bulls": "BUL",
        "Cobras": "COB",
        "Ducks": "DUC",
        "Eagles": "EAG",
        "Flames": "FLA",
        "Hawks": "HAW",
        "Kings": "KIN",
        "Lions": "LIO",
        "Lumberjacks": "LUM",
        "Panthers": "PAN",
        "Pirates": "PIR",
        "Sharks": "SHA",
        "Spartans": "SPA",
        "Storm": "STO",
        "Whitecaps": "WHI",
        # "ASC": "Ascension",
        # "BUL": "Bulls",
        # "COB": "Cobras",
        # "DUC": "Ducks",
        # "EAG": "Eagles",
        # "FLA": "Flames",
        # "HAW": "Hawks",
        # "KIN": "Kings",
        # "LIO": "Lions",
        # "LUM": "Lumberjacks",
        # "PAN": "Panthers",
        # "PIR": "Pirates",
        # "SHA": "Sharks",
        # "SPA": "Spartans",
        # "STO": "Storm",
        # "WHI": "Whitecaps",
    },
    
    "aaa": {
        "Bobcats": "BOB",
        "Bulldogs": "BDG",
        "Dolphins": "DOL",
        "Entropy": "ENT",
        "Geese": "GSE",
        "Heat": "HEA",
        "Knights": "KNI",
        "Osprey": "OSP",
        "Owls": "OWL",
        "Pioneers": "PIO",
        "Raiders": "RAI",
        "Thunder": "THU",
        "Tigers": "TIG",
        "Trojans": "TRO",
        "Tundra": "TUN",
        "Vipers": "VIP",
        # "BOB": "Bobcats",
        # "BDG": "Bulldogs",
        # "DOL": "Dolphins",
        # "ENT": "Entropy",
        # "GSE": "Geese",
        # "HEA": "Heat",
        # "KNI": "Knights",
        # "OSP": "Osprey",
        # "OWL": "Owls",
        # "PIO": "Pioneers",
        # "RAI": "Raiders",
        # "THU": "Thunder",
        # "TIG": "Tigers",
        # "TRO": "Trojans",
        # "TUN": "Tundra",
        # "VIP": "Vipers",
    },

    "aa": {
        "Avalanche": "AVA",
        "Bandits": "BAN",
        "Barracuda": "BAR",
        "Dukes": "DUK",
        "Falcons": "FAL",
        "Herons": "HER",
        "Inferno": "INF",
        "Jaguars": "JAG",
        "Lightning": "LGH",
        "Lynx": "LNX",
        "Mustangs": "MUS",
        "Pulsars": "PUL",
        "Pythons": "PYT",
        "Voyagers": "VOY",
        "Vultures": "VUL",
        "Warriors": "WAR",
        # "AVA": "Avalanche",
        # "BAN": "Bandits",
        # "BAR": "Barracuda",
        # "DUK": "Dukes",
        # "FAL": "Falcons",
        # "HER": "Herons",
        # "INF": "Inferno",
        # "JAG": "Jaguars",
        # "LGH": "Lightning",
        # "LNX": "Lynx",
        # "MUS": "Mustangs",
        # "PUL": "Pulsars",
        # "PYT": "Pythons",
        # "VOY": "Voyagers",
        # "VUL": "Vultures",
        # "WAR": "Warriors",
    },

    "a": {
        "Cardinals": "CAR",
        "Cougars": "COU",
        "Embers": "EMB",
        "Eskimos": "ESK",
        "Genesis": "GEN",
        "Gulls": "GUL",
        "Jesters": "JES",
        "Leopards": "LEO",
        "Miners": "MIN",
        "Pelicans": "PEL",
        "Rattlers": "RAT",
        "Ravens": "RAV",
        "Stallions": "STA",
        "Tempest": "TEM",
        "Titans": "TTN",
        "Wranglers": "WRA",
        # "CAR": "Cardinals",
        # "COU": "Cougars",
        # "EMB": "Embers",
        # "ESK": "Eskimos",
        # "GEN": "Genesis",
        # "GUL": "Gulls",
        # "JES": "Jesters",
        # "LEO": "Leopards",
        # "MIN": "Miners",
        # "PEL": "Pelicans",
        # "RAT": "Rattlers",
        # "RAV": "Ravens",
        # "STA": "Stallions",
        # "TEM": "Tempest",
        # "TTN": "Titans",
        # "WRA": "Wranglers",
    },

    "independent": {
        "Admirals": "ADM",
        "Beavers": "BEA",
        "Centurions": "CEN",
        "Cyclones": "CYC",
        "Dragons": "DRA",
        "Galaxy": "GAL",
        "Grizzlies": "GRI",
        "Rhinos": "RHI",
        "Scorpions": "SCO",
        "Sockeyes": "SCK",
        "Thrashers": "THR",
        "Toucans": "TOU",
        "Wildcats": "WIL",
        "Wizards": "WIZ",
        "Wolves": "WOL",
        "Yellow Jackets": "YLJ",
        # "ADM": "Admirals",
        # "BEA": "Beavers",
        # "CEN": "Centurions",
        # "CYC": "Cyclones",
        # "DRA": "Dragons",
        # "GAL": "Galaxy",
        # "GRI": "Grizzlies",
        # "RHI": "Rhinos",
        # "SCO": "Scorpions",
        # "SCK": "Sockeyes",
        # "THR": "Thrashers",
        # "TOU": "Toucans",
        # "WIL": "Wildcats",
        # "WIZ": "Wizards",
        # "WOL": "Wolves",
        # "YLJ": "Yellow Jackets",
    },
    
    "maverick": {
        "Camels": "CAM",
        "Captains": "CAP",
        "Hornets": "HOR",
        "Jackrabbits": "JAC",
        "Macaws": "MAC",
        "Mages": "MAG",
        "Otters": "OTT",
        "Pandas": "PND",
        "Piranhas": "PRN",
        "Raptors": "RAP",
        "Samurai": "SAM",
        "Solar": "SOL",
        "Terriers": "TER",
        "Tides": "TID",
        "Yetis": "YET",
        "Zebras": "ZEB",
        # "CAM": "Camels",
        # "CAP": "Captains",
        # "HOR": "Hornets",
        # "JAC": "Jackrabbits",
        # "MAC": "Macaws",
        # "MAG": "Mages",
        # "OTT": "Otters",
        # "PND": "Pandas",
        # "PRN": "Piranhas",
        # "RAP": "Raptors",
        # "SAM": "Samurai",
        # "SOL": "Solar",
        # "TER": "Terriers",
        # "TID": "Tides",
        # "YET": "Yetis",
        # "ZEB": "Zebras",
    },

    "renegade": {
        "Comets": "COM",
        "Coyotes": "COY",
        "Fireflies": "FIR",
        "Gorillas": "GOR",
        "Harriers": "HAR",
        "Hounds": "HOU",
        "Hurricanes": "HUR",
        "Koalas": "KOA",
        "Pilots": "PIL",
        "Puffins": "PUF",
        "Stingrays": "STI",
        "Vikings": "VIK",
        "Warthogs": "WRT",
        "Werewolves": "WWL",
        "Witches": "WIT",
        "Wolverines": "WVN",
        # "COM": "Comets",
        # "COY": "Coyotes",
        # "FIR": "Fireflies",
        # "GOR": "Gorillas",
        # "HAR": "Harriers",
        # "HOU": "Hounds",
        # "HUR": "Hurricanes",
        # "KOA": "Koalas",
        # "PIL": "Pilots",
        # "PUF": "Puffins",
        # "STI": "Stingrays",
        # "VIK": "Vikings",
        # "WRT": "Warthogs",
        # "WWL": "Werewolves",
        # "WIT": "Witches",
        # "WVN": "Wolverines",
    },

    "paladin": {
        "Badgers": "BAD",
        "Buzzards": "BUZ",
        "Cosmos": "COS",
        "Cubs": "CUB",
        "Dragonflies": "DGF",
        "Foxes": "FOX",
        "Griffins": "GRF",
        "Hammerheads": "HAM",
        "Jackals": "JKL",
        "Ninjas": "NIN",
        "Penguins": "PEN",
        "Quakes": "QUA",
        "Roadrunners": "RDR",
        "Sailors": "SAI",
        "Sorcerers": "SOR",
        "Wildebeests": "WDB",
        # "BAD": "Badgers",
        # "BUZ": "Buzzards",
        # "COS": "Cosmos",
        # "CUB": "Cubs",
        # "DGF": "Dragonflies",
        # "FOX": "Foxes",
        # "GRF": "Griffins",
        # "HAM": "Hammerheads",
        # "JKL": "Jackals",
        # "NIN": "Ninjas",
        # "PEN": "Penguins",
        # "QUA": "Quakes",
        # "RDR": "Roadrunners",
        # "SAI": "Sailors",
        # "SOR": "Sorcerers",
        # "WDB": "Wildebeests",
    },
}